<?php
if (function_exists('acf_add_local_field_group')) :
    acf_add_local_field_group(array(
        'key' => 'group_602e3814eaa06',
        'title' => 'Mediaplanet ClientLogos Settings',
        'fields' => array(
            array(
                'key' => 'field_60337660f6450',
                'label' => __('Homepage Settings', 'vam'),
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'test',
                'label' => 'Title text',
                'name' => 'test',
                'type' => 'text',
                'menu_order' => 1,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'active' => 1,
            ),
            array(
                'key' => 'field_60337693f64511',
                'label' => __('Show logos on Homepage', 'vam'),
                'name' => 'show_ads_on_homepage',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Enable',
                'default_value' => 1,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'uploader_logos',
                'label' => 'Upload logos here',
                'name' => 'uploader_logos',
                'menu_order' => 1,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'active' => 1,
                'type' => 'repeater',
                'instructions' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'img',
                        'label' => 'Logo',
                        'name' => 'img',
                        'type' => 'file',
                    ),
                    array(
                        'key' => 'url',
                        'label' => 'URL',
                        'name' => 'url',
                        'type' => 'text',
                    ),
                ),
                'button_label' => 'Add',
                'min' => '',
                'max' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'vam-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
endif;
